from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from alfred.connectors.google_calendar_connector import GoogleCalendarConnector
from alfred.schemas.interview_prep import InterviewCalendarEvent
from alfred.services.google_oauth import load_credentials, persist_credentials


def _utcnow() -> datetime:
    return datetime.utcnow().replace(tzinfo=timezone.utc)


@dataclass
class InterviewCalendarService:
    """Create calendar events for interviews when calendar credentials exist."""

    def _connector(self) -> GoogleCalendarConnector | None:
        creds = load_credentials(namespace="calendar")
        if creds is None:
            return None
        return GoogleCalendarConnector(
            creds,
            user_id=None,
            on_credentials_refreshed=lambda c: persist_credentials(None, c, namespace="calendar"),
        )

    def create_interview_event(
        self,
        *,
        company: str,
        role: str,
        start: datetime,
        meeting_link: str | None = None,
    ) -> InterviewCalendarEvent | None:
        connector = self._connector()
        if connector is None:
            return None

        if start.tzinfo is None:
            start = start.replace(tzinfo=timezone.utc)

        summary = f"Interview — {company} ({role})"
        description = "Generated by Alfred."
        if meeting_link:
            description += f"\n\nMeeting: {meeting_link}"

        reminders = [
            {"method": "popup", "minutes": 60},
            {"method": "popup", "minutes": 24 * 60},
            {"method": "popup", "minutes": 3 * 24 * 60},
        ]

        async def _run() -> dict[str, Any]:
            return await connector.create_event(
                summary=summary,
                start=start,
                timezone=None,
                attendees=None,
                description=description,
                location=meeting_link or "",
                reminders=reminders,
            )

        res = asyncio.run(_run())
        event_id = str(res.get("event_id") or "")
        if not event_id:
            return None
        return InterviewCalendarEvent(
            event_id=event_id,
            event_link=res.get("event_link"),
            meet_link=res.get("meet_link") or meeting_link,
            created_at=_utcnow(),
        )


__all__ = ["InterviewCalendarService"]
